### ISSUE TITLE
Best way to implement long scripts?

### ISSUE THREAD

**Issue by FatherShawn** [devinci-code/ahoy#17]
This is the script that `Docker Quickstart Terminal` runs to launch an instance of a docker machine on OSX:
[start.sh.zip](https://github.com/devinci-code/ahoy/files/74916/start.sh.zip)

Is the best way to implement something like this to build a long command in an include file along the lines of your example at https://github.com/devinci-code/ahoy/blob/master/examples/confirmation.ahoy.yml or did you have something else in mind?  Project init scripts will be another example of longer commands.

**Comment by frankcarey** [comment]
You've got 3 options basically:
1) Put the entire script into the file directly. - Can be a bit cluttered if the script is long. Just make sure you use `cmd: |` so the line breaks work properly. For me, your example would be a bit long to include directly.
2) Just reuse an existing script file as-is but call it as a command in ahoy to give a better UI and help text. - This is probably a good option for this script since it's already written and works (I assume). I'm in the habbit of including these types of files, and more in an .ahoy/ folder in the project root to keep things clean.
```
docker-init:
  cmd: bash .ahoy/location_of_existing_script.sh [ARGS]
```
3) Split the script up into independent parts as separate ahoy commands (if that makes sense to do) - In your example perhaps that doesn't make sense.
4) Implement the script as a side-loaded command from another ahoy file. 
```
docker-init:
  cmd: ahoy -f ./someotherfile.ahoy.yml mycommand args
``` 

Same thing for a project init file.. if you have an example of one of those I can make some suggestions there too, but basically you could just create a `project-init` command as well.

**Comment by FatherShawn** [comment]
Thanks, Frank. This makes sense. For project init I'm thinking about the script behind `dsh init`.  The idea of a `.ahoy` directory makes total sense per project. I was probably trying to make ahoy do too much - you aren't totally replacing shell scripting just making short scripts easier and giving all script interactions a common interface.
